### ISSUE TITLE
Publish test coverage in CI

### ISSUE THREAD

**Issue by uniqueg** [ohsu-comp-bio/py-tes#45]
@kellrott: Server-side this already seems to be set up for Coveralls. However, when migrating our services and tools to GitHub Actions from Travis CI, we had a hard time getting Coveralls to work and migrated our services to [Codecov](https://about.codecov.io/) instead. I could try again to make it work with Coveralls if you like (it's a little while ago) - but otherwise Codecov has worked really nice for us.

In that case, you would have to set this up on the Codecov server though, @kellrott, and set a repository secret. And then replace the last task in the CI workflow in the [`0.5.0` release branch](https://github.com/ohsu-comp-bio/py-tes/tree/release-0.5.0) with the following two (you may of course need to change the name of the secret if you did not use `CODECOV_TOKEN`):

```yaml
      - name: Run unit tests
        run: |
          coverage run --source tes -m pytest -W ignore::DeprecationWarning
          coverage xml
      - name: Submit coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
```

Either way, please let me know.
